In [4]:
import pandas as pd
import requests

import imblearn

In [7]:
import pickle
import requests

# URL of the .sav file
url = "https://raw.githubusercontent.com/glenvj-j/Saudi-Arabia-Used-Car-Regression-Prediction/main/Streamlit/Model_Saudi_Arabia_Used_Cars.sav"

# Fetch the file from the URL
response = requests.get(url)
model_loaded = pickle.loads(response.content)


# # Check if the file was downloaded successfully
# if response.status_code == 200:
#     # Load the model using pickle
#     model_loaded = pickle.loads(response.content)
#     print("Model loaded successfully!")
# else:
#     print(f"Failed to fetch the model. HTTP Status Code: {response.status_code}")

In [10]:
pip freeze > requirements.txt

Note: you may need to restart the kernel to use updated packages.

In [8]:
model_loaded

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('pipe_ordinal_robust',
                                                  Pipeline(steps=[('ordinal',
                                                                   OrdinalEncoder(mapping=[{'col': 'Options',
                                                                                            'data_type': dtype('O'),
                                                                                            'mapping': Standard     1
Semi Full    2
Full         3
dtype: int64}])),
                                                                  ('robust',
                                                                   RobustScaler())]),
                                                  ['Options']),
                                                 ('Binary', BinaryEncoder(),
                                                  ['Type', 'Region', 'Make']),
                                                 ('robust', RobustScaler(),
                                                  ['Mileage', 'Engine_Size',
                                                   'Year']),
                                                 ('onehot',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['Gear_Type', 'Origin'])])),
                ('modeling',
                 <catboost.core.CatBoostRegressor object at 0x305df92e0>)])

In [3]:
df = pd.read_csv('clean_dataset_arab_used_car.csv').loc[:,'Type':]

In [4]:
pd.set_option('display.max_colwidth', None)
listItem = []
for col in df.columns :
    listItem.append( [col, df[col].nunique(), df[col].unique()])

tabel1Desc = pd.DataFrame(columns=['Column Name', 'Number of Unique', 'Unique Sample'],
                     data=listItem)
tabel1Desc

,Column Name,Number of Unique,Unique Sample
0,Type,285,"[Yukon, Optima, CX3, Cayenne S, Sonata, Avalon, C300, Land Cruiser, LS, FJ, Tucson, Pajero, Azera, Focus, 5, Spark, Accent, ML, Corolla, Tahoe, A, Altima, Expedition, Senta fe, Liberty, X, Land Cruiser Pickup, VTC, Malibu, The 5, Patrol, Grand Cherokee, Previa, MKZ, Datsun, Hilux, Edge, 6, Innova, Navara, G80, Carnival, Camaro, Accord, Sunny, Taurus, Camry, Elantra, Flex, S, Cerato, Land Cruiser 70, 3, Pick up, Charger, H6, Hiace, CX9, Yaris, Sierra, CT-S, Sylvian Bus, ES, Navigator, The 7, Creta, CS35, The 3, Sedona, Victoria, Prestige, Safrane, Cadenza, Silverado, Rio, Maxima, X-Trail, Cruze, Seven, Prado, Caprice, LX, C, Impala, QX, Blazer, H1, Rav4, The M, Genesis, Fusion, Pathfinder, Traverse, Suburban, Furniture, Civic, Echo Sport, Challenger, CL, Wrangler, ...]"
1,Region,27,"[Riyadh, Hafar Al-Batin, Abha, Makkah, Dammam, Jeddah, Khobar, Al-Baha, Jazan, Aseer, Al-Medina, Al-Namas, Qassim, Al-Ahsa, Sabya, Al-Jouf, Najran, Tabouk, Taef, Jubail, Wadi Dawasir, Hail, Arar, Yanbu, Besha, Sakaka, Qurayyat]"
2,Make,53,"[GMC, Kia, Mazda, Porsche, Hyundai, Toyota, Chrysler, Lexus, Mitsubishi, Ford, MG, Chevrolet, Mercedes, Nissan, Jeep, BMW, Lincoln, Genesis, Honda, Zhengzhou, Dodge, HAVAL, Cadillac, Changan, Renault, INFINITI, Audi, Land Rover, Mercury, BYD, Volkswagen, Victory Auto, Aston Martin, Suzuki, Geely, Isuzu, Daihatsu, Other, Hummer, GAC, Lifan, Bentley, Maserati, Chery, Jaguar, Peugeot, Foton, MINI, Å koda, Fiat, Iveco, FAW, Great Wall]"
3,Gear_Type,2,"[Automatic, Manual]"
4,Origin,4,"[Saudi, Gulf Arabic, Other, Missing]"
5,Options,3,"[Full, Semi Full, Standard]"
6,Year,19,"[2014, 2015, 2019, 2012, 2016, 2013, 2011, 2008, 2020, 2018, 2021, 2017, 2010, 2007, 2009, 2003, 2005, 2006, 2004]"
7,Engine_Size,60,"[8.0, 2.4, 2.0, 4.8, 3.5, 5.7, 4.6, 4.0, 3.0, 1.6, 1.5, 1.4, 6.2, 2.5, 5.3, 5.4, 3.3, 3.7, 3.6, 2.7, 3.8, 5.5, 2.6, 1.8, 3.2, 1.0, 6.0, 2.2, 5.6, 5.0, 2.9, 4.1, 1.7, 4.4, 4.5, 3.4, 6.1, 1.2, 9.0, 1.9, 4.3, 2.8, 7.5, 5.8, 1.1, 8.5, 2.3, 1.3, 7.2, 7.0, 6.3, 5.2, 6.4, 4.7, 2.1, 3.1, 6.6, 3.9, 8.7, 4.9]"
8,Mileage,1144,"[80000, 220000, 25000, 189000, 155, 110864, 200, 79000, 299000, 17000, 85000, 74715, 284000, 98000, 3400, 108, 204000, 139240, 296, 105920, 10000, 18500, 292000, 270000, 350000, 247000, 92000, 307801, 62000, 38000, 208000, 11000, 245000, 156000, 228000, 98100, 182000, 210800, 88000, 70000, 115, 91440, 45000, 50100, 35449, 180, 66200, 89000, 349000, 105000, 130000, 212000, 139740, 256, 73000, 866, 216, 148000, 188257, 117000, 211257, 135000, 290000, 43632, 153000, 126000, 180000, 108000, 122000, 53000, 181000, 13800, 9000, 168000, 86500, 192692, 48000, 38920, 32000, 3000, 334000, 34000, 229000, 151000, 201000, 130, 147000, 101732, 145, 9800, 231000, 92412, 128, 200000, 124000, 79968, 240000, 63000, 132000, 71000, ...]"
9,Negotiable,1,[False]
10,Price,270,"[120000, 42000, 58000, 85000, 48000, 81500, 55000, 145000, 38000, 140000, 65000, 76000, 32000, 23000, 20000, 45000, 30000, 149000, 179000, 22000, 49500, 52000, 25000, 72000, 105000, 99000, 57000, 110000, 56500, 90000, 71500, 29000, 62000, 141000, 60000, 93000, 68000, 50000, 69000, 121500, 51000, 109000, 47000, 88000, 15000, 142000, 53000, 39000, 78500, 35000, 45500, 125000, 63000, 80000, 44000, 54000, 37000, 79000, 70000, 81000, 68500, 33500, 33000, 118000, 36500, 75000, 61500, 44500, 107000, 102000, 99500, 122000, 21000, 77000, 100000, 59500, 119000, 38500, 165000, 72910, 35500, 66000, 76500, 27000, 95000, 115000, 26000, 69500, 28500, 40000, 27500, 89000, 49000, 138000, 126000, 36000, 139000, 56000, 135000, 43000, ...]"

In [5]:
df.head()

,Type,Region,Make,Gear_Type,Origin,Options,Year,Engine_Size,Mileage,Negotiable,Price
0,Yukon,Riyadh,GMC,Automatic,Saudi,Full,2014,8.0,80000,False,120000
1,Optima,Hafar Al-Batin,Kia,Automatic,Saudi,Semi Full,2015,2.4,220000,False,42000
2,CX3,Abha,Mazda,Automatic,Saudi,Semi Full,2019,2.0,25000,False,58000
3,Cayenne S,Riyadh,Porsche,Automatic,Saudi,Full,2012,4.8,189000,False,85000
4,Sonata,Riyadh,Hyundai,Automatic,Saudi,Full,2016,2.4,155,False,48000

# Origin and Region

In [6]:
list_Origin = []
list_Region = []

for origin in sorted(df['Origin'].unique()) :
    region = sorted(list(df[df["Origin"]==origin]['Region'].unique()))
    list_Region.append(region)
    list_Origin.append(origin)

df_origin_region = pd.DataFrame()
df_origin_region['Origin'] = list_Origin
df_origin_region['Region'] = list_Region
df_origin_region = df_origin_region.loc[[0,3,2]]
df_origin_region

,Origin,Region
0,Gulf Arabic,"[Al-Ahsa, Al-Baha, Al-Medina, Aseer, Dammam, Hafar Al-Batin, Hail, Jeddah, Jubail, Khobar, Makkah, Najran, Qassim, Qurayyat, Riyadh, Tabouk]"
3,Saudi,"[Abha, Al-Ahsa, Al-Baha, Al-Jouf, Al-Medina, Al-Namas, Arar, Aseer, Besha, Dammam, Hafar Al-Batin, Hail, Jazan, Jeddah, Jubail, Khobar, Makkah, Najran, Qassim, Qurayyat, Riyadh, Sabya, Sakaka, Tabouk, Taef, Wadi Dawasir, Yanbu]"
2,Other,"[Abha, Al-Ahsa, Al-Baha, Al-Jouf, Al-Medina, Aseer, Besha, Dammam, Hail, Jazan, Jeddah, Jubail, Khobar, Makkah, Najran, Qassim, Qurayyat, Riyadh, Tabouk, Taef, Wadi Dawasir, Yanbu]"

In [7]:
df_origin_region['Origin'].tolist()

['Gulf Arabic', 'Saudi', 'Other']

In [8]:
df_origin_region[df_origin_region['Origin'] == 'Gulf Arabic']['Region'].tolist()[0]

['Al-Ahsa',
 'Al-Baha',
 'Al-Medina',
 'Aseer',
 'Dammam',
 'Hafar Al-Batin',
 'Hail',
 'Jeddah',
 'Jubail',
 'Khobar',
 'Makkah',
 'Najran',
 'Qassim',
 'Qurayyat',
 'Riyadh',
 'Tabouk']

# Make & Type

In [9]:
list_brand = []
list_type = []

for brand in sorted(df['Make'].unique()) :
    type = sorted(list(df[df['Make']==brand]['Type'].unique()))
    list_type.append(type)
    list_brand.append(brand)

df_brand_type = pd.DataFrame()
df_brand_type['Make'] = list_brand
df_brand_type['Type'] = list_type
df_brand_type

,Make,Type
0,Aston Martin,[DB9]
1,Audi,"[A3, A4, A5, A6, A7, A8, Q5, Q7, S5]"
2,BMW,"[The 3, The 4, The 5, The 6, The 7, The M, X, Z]"
3,BYD,[F3]
4,Bentley,[Flying Spur]
5,Cadillac,"[ATS, CT-S, CT4, CT5, CT6, Escalade, XT5]"
6,Changan,"[CS35, CS35 Plus, CS75, CS85, CS95, Eado, Seven]"
7,Chery,[Tiggo]
8,Chevrolet,"[Aveo, Blazer, Camaro, Caprice, Colorado, Cruze, Impala, Kaptiva, Malibu, Silverado, Spark, Suburban, Tahoe, Traverse]"
9,Chrysler,"[300, C200, C300, S300, SRT]"
10,Daihatsu,"[Delta, Gran Max]"
11,Dodge,"[Challenger, Charger, Durango, Nitro, Ram]"
12,FAW,"[B50, X40]"
13,Fiat,"[500, Doblo]"
14,Ford,"[Echo Sport, Edge, Expedition, Explorer, F150, Flex, Focus, Fusion, Marquis, Mustang, Other, Ranger, Taurus, Van, Vego, Victoria]"
15,Foton,"[Mini Van, Suvana]"
16,GAC,[GS3]
17,GMC,"[Acadia, Safari, Sierra, Suburban, Terrain, Yukon]"
18,Geely,"[Azkarra, Coolray, EC7, Emgrand, GC7, GS, Other, X7]"
19,Genesis,"[Coupe, G70, G80, Platinum, Prestige, Prestige Plus, Royal]"
20,Great Wall,[Power]
21,HAVAL,"[H2, H6]"
22,Honda,"[Accord, CRV, City, Civic, HRV, Odyssey, Other, Pilot]"
23,Hummer,[H3]
24,Hyundai,"[Accent, Avante, Azera, Bus County, Coupe S, Creta, Elantra, Genesis, H1, Kona, Other, Senta fe, Sonata, Tucson, Tuscani, Veloster, i40]"
25,INFINITI,"[FX, Q, QX]"
26,Isuzu,"[D-MAX, Dyna]"
27,Iveco,[Daily]
28,Jaguar,"[F-Pace, XF, XJ]"
29,Jeep,"[Cherokee, Compass, Grand Cherokee, Liberty, Wrangler]"
30,Kia,"[Cadenza, Carens, Carenz, Carnival, Cerato, Cores, K5, Mohave, Opirus, Optima, Pegas, Picanto, Rio, Sedona, Seltos, Sorento, Soul, Sportage, Stinger]"
31,Land Rover,[Range Rover]
32,Lexus,"[ES, GS, GX, IS, LS, LX, NX, RX, UX]"
33,Lifan,[LF X60]
34,Lincoln,"[MKS, MKX, MKZ, Navigator]"
35,MG,"[3, 360, 5, 6, GS, HS, RX5, RX8, ZS]"
36,MINI,"[Copper, Countryman]"
37,Maserati,[Quattroporte]
38,Mazda,"[3, 6, CX3, CX5, CX7, CX9]"
39,Mercedes,"[A, C, CL, CLA, CLS, E, GL, GLC, GLE, ML, S, Viano]"
40,Mercury,"[Grand Marquis, Milan]"
41,Mitsubishi,"[ASX, Attrage, L200, L300, Lancer, Montero, Nativa, Other, Pajero]"
42,Nissan,"[Altima, Armada, Bus Urvan, Datsun, Juke, KICKS, Land Cruiser Pickup, Maxima, Navara, Pathfinder, Patrol, Sentra, Sunny, Sylvian Bus, VTC, X-Terra, X-Trail, Z350, Z370]"
43,Other,[Other]
44,Peugeot,"[3008, 301, 5008]"
45,Porsche,"[Cayenne, Cayenne S, Cayenne Turbo, Cayman, Macan, Panamera]"
46,Renault,"[Dokker, Duster, Fluence, Koleos, Megane, Safrane, Symbol]"
47,Suzuki,"[APV, Dzire, Ertiga, Grand Vitara, Jimny]"
48,Toyota,"[4Runner, Aurion, Avalon, Avanza, Camry, Ciocca, Coaster, Corolla, FJ, Furniture, Hiace, Hilux, Innova, Land Cruiser, Land Cruiser 70, Land Cruiser Pickup, Prado, Previa, Prius, Rav4, Rush, Yaris]"
49,Victory Auto,[Van R]
50,Volkswagen,"[Beetle, CC, Golf, Jetta, Passat, Tiguan, Touareg]"
51,Zhengzhou,[Pick up]
52,Å koda,[Superb]

In [10]:
df_brand_type['Make'].tolist()

['Aston Martin',
 'Audi',
 'BMW',
 'BYD',
 'Bentley',
 'Cadillac',
 'Changan',
 'Chery',
 'Chevrolet',
 'Chrysler',
 'Daihatsu',
 'Dodge',
 'FAW',
 'Fiat',
 'Ford',
 'Foton',
 'GAC',
 'GMC',
 'Geely',
 'Genesis',
 'Great Wall',
 'HAVAL',
 'Honda',
 'Hummer',
 'Hyundai',
 'INFINITI',
 'Isuzu',
 'Iveco',
 'Jaguar',
 'Jeep',
 'Kia',
 'Land Rover',
 'Lexus',
 'Lifan',
 'Lincoln',
 'MG',
 'MINI',
 'Maserati',
 'Mazda',
 'Mercedes',
 'Mercury',
 'Mitsubishi',
 'Nissan',
 'Other',
 'Peugeot',
 'Porsche',
 'Renault',
 'Suzuki',
 'Toyota',
 'Victory Auto',
 'Volkswagen',
 'Zhengzhou',
 'Å koda']

In [11]:
df_brand_type[df_brand_type['Make'] == 'Honda']['Type'].tolist()[0]

['Accord', 'CRV', 'City', 'Civic', 'HRV', 'Odyssey', 'Other', 'Pilot']

In [12]:
df.head()

,Type,Region,Make,Gear_Type,Origin,Options,Year,Engine_Size,Mileage,Negotiable,Price
0,Yukon,Riyadh,GMC,Automatic,Saudi,Full,2014,8.0,80000,False,120000
1,Optima,Hafar Al-Batin,Kia,Automatic,Saudi,Semi Full,2015,2.4,220000,False,42000
2,CX3,Abha,Mazda,Automatic,Saudi,Semi Full,2019,2.0,25000,False,58000
3,Cayenne S,Riyadh,Porsche,Automatic,Saudi,Full,2012,4.8,189000,False,85000
4,Sonata,Riyadh,Hyundai,Automatic,Saudi,Full,2016,2.4,155,False,48000

In [20]:
df.groupby('Region')[['Price']].mean().reset_index().sort_values(by='Price',ascending=False)

            Region         Price
22          Sakaka  90000.000000
17          Najran  78545.454545
9           Dammam  75335.792779
25    Wadi Dawasir  72333.333333
15          Khobar  70741.250000
7            Aseer  69119.402985
18          Qassim  68777.272727
20          Riyadh  67514.700725
13          Jeddah  66745.196035
12           Jazan  65115.384615
1          Al-Ahsa  63276.288660
16          Makkah  61628.893939
10  Hafar Al-Batin  60454.545455
0             Abha  60360.000000
2          Al-Baha  60125.000000
11            Hail  59526.315789
4        Al-Medina  56509.708738
3          Al-Jouf  56045.454545
14          Jubail  55910.714286
24            Taef  54661.764706
23          Tabouk  54488.095238
6             Arar  52400.000000
5         Al-Namas  51444.444444
8            Besha  49666.666667
26           Yanbu  45900.000000
19        Qurayyat  44333.333333
21           Sabya  35000.000000

In [14]:
sorted(df['Year'].unique())

[2003,
 2004,
 2005,
 2006,
 2007,
 2008,
 2009,
 2010,
 2011,
 2012,
 2013,
 2014,
 2015,
 2016,
 2017,
 2018,
 2019,
 2020,
 2021]

In [21]:
Type_price_average = df.groupby('Type')[['Price']].mean().reset_index().sort_values(by='Price',ascending=False)
Type_price_average

            Type     Price
90           DB9  180000.0
53           CT5  179000.0
119  Flying Spur  175000.0
127          GLC  173000.0
42            CL  170000.0
..           ...       ...
187       Opirus   16000.0
150        Jimny   16000.0
185        Nitro   16000.0
125          GC7   15000.0
242       Superb   15000.0

[285 rows x 2 columns]

In [22]:
df

,Type,Region,Make,Gear_Type,Origin,Options,Year,Engine_Size,Mileage,Negotiable,Price
0,Yukon,Riyadh,GMC,Automatic,Saudi,Full,2014,8.0,80000,False,120000
1,Optima,Hafar Al-Batin,Kia,Automatic,Saudi,Semi Full,2015,2.4,220000,False,42000
2,CX3,Abha,Mazda,Automatic,Saudi,Semi Full,2019,2.0,25000,False,58000
3,Cayenne S,Riyadh,Porsche,Automatic,Saudi,Full,2012,4.8,189000,False,85000
4,Sonata,Riyadh,Hyundai,Automatic,Saudi,Full,2016,2.4,155,False,48000
...,...,...,...,...,...,...,...,...,...,...,...
3187,CX9,Qassim,Mazda,Automatic,Saudi,Full,2020,2.0,9500,False,132000
3188,Suburban,Riyadh,GMC,Automatic,Saudi,Full,2006,5.3,86000,False,50000
3189,X-Trail,Jeddah,Nissan,Automatic,Saudi,Standard,2018,2.5,78794,False,68000
3190,Yukon,Dammam,GMC,Automatic,Saudi,Full,2016,5.3,48000,False,145000
3191,RX,Dammam,Lexus,Automatic,Gulf Arabic,Full,2016,2.5,81000,False,154000

In [2]:
pip install googleapiclient

ERROR: Could not find a version that satisfies the requirement googleapiclient (from versions: none)
ERROR: No matching distribution found for googleapiclient
Note: you may need to restart the kernel to use updated packages.

In [1]:
from __future__ import print_function
from googleapiclient.discovery import build
from oauth2client.service_account import ServiceAccountCredentials

scope = ['https://www.googleapis.com/auth/drive.readonly']

credentials = ServiceAccountCredentials.from_json_keyfile_name('service_account_key.json', scope)

# https://developers.google.com/drive/api/v3/quickstart/python
service = build('drive', 'v3', credentials=credentials)

# Call the Drive v3 API
results = service.files().list(
    fields="*",corpora = 'drive',supportsAllDrives = True, driveId = "YOUR_DRIVE_ID", includeItemsFromAllDrives = True).execute()
items = results.get('files', [])

if not items:
    print('No files found.')
else:
    print('Files:')
    for item in items:
        print(u'{0} ({1})'.format(item['name'], item['id']))

ModuleNotFoundError: No module named 'googleapiclient'